// I have no clue why I thought that this is needed but here we are

enum
{
	EFFECT_OFF = 0,
	EFFECT_SPARKLE,
	EFFECT_FIRETRAIL,
	EFFECT_SWITCH,

	DETECTION_NONE = 0,
	DETECTION_NAMECHANGE,
	DETECTION_AUTOJOINTEAM,
	DETECTION_NOTIFYONJOIN,
	DETECTION_ADBOT
};